In [1]:
from operator import attrgetter
import spacy
from src.features.clean import remove_html
import numpy as np

% load_ext autoreload
% autoreload 2

In [4]:
!python -m spacy download ru_core_news_md

2022-01-11 16:20:12.859497: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-01-11 16:20:12.859529: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


  Using cached pymorphy2-0.9.1-py3-none-any.whl (55 kB)
  Using cached pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2 MB)
  Using cached DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13724 sha256=264b6c969bc456471d8a082bf1f60f57512d2d0dcabf52055347f4cf9cf110d2
  Stored in directory: c:\users\uiqko\appdata\local\pip\cache\wheels\70\4a\46\1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built docopt
[+] Download and installation successful
You can now load the package via spacy.load('ru_core_news_md')


In [2]:

nlp = spacy.load('ru_core_news_md')

doc = nlp(
    'Обязанности: Своевременная подача автомобиля; Организация поездок; Планирование оптимального маршрута '
    'передвижения с учетом особенностей дорожной ситуации; Поддержание чистоты в салоне автомобиля; Поддержание и '
    'контроль исправного состояния автомобиля. Требования: Стаж вождения автомобиля от 5-ти лет; Наличие опыта работы '
    'персональным водителем на автомобилях представительского класса; Водительское удостоверение категории В; '
    'Пунктуальность, ответственность, дисциплинированность, доброжелательность. Условия: Работа на автомобиле '
    'представительского класса; Ненормированный рабочий день, как правило воскресенье стабильно выходной  Отпуск во '
    'время отсутствия руководителя   Прошу в сопроводительном письме указать где территориально вы проживаете '.lower()
)

In [2]:
import spacy

In [3]:
nlp = spacy.load('ru_core_news_md')

In [4]:
doc = nlp('<p attr="val">Привет мир</p>!')

In [5]:
for tok in doc:
    print(tok.text, tok.is_punct)

< False
p False
attr="val">Привет False
мир</p False
> False
! True


In [7]:
doc = nlp(remove_html('<p attr="val">Привет мир</p>!'))
for tok in doc:
    print(tok.text, tok.is_punct)

Привет False
мир False
! True


In [4]:
np.mean(list(map(attrgetter('vector'), doc)), axis=1)

array([-0.01988309,  0.        , -0.00226534, -0.02913788,  0.00833846,
        0.        , -0.00978985, -0.03960135,  0.        ,  0.00108756,
        0.00523152, -0.00910878, -0.04765929,  0.00898744,  0.00250398,
        0.02227592, -0.01148476,  0.01401027,  0.        , -0.02737234,
        0.01751405,  0.00898744,  0.00833846,  0.00833846,  0.        ,
       -0.02737234,  0.00898744,  0.00613136, -0.01176543,  0.00705248,
        0.00833846,  0.        ,  0.00021279,  0.        , -0.02073753,
        0.01920758,  0.00833846,  0.00898744,  0.        ,  0.00898744,
        0.        ,  0.01006426,  0.01376081,  0.02952036, -0.0196102 ,
       -0.01040047,  0.00898744, -0.0116934 , -0.01157035, -0.02739305,
        0.        ,  0.00764168,  0.00764168,  0.01141134,  0.00898744,
        0.        , -0.01289268,  0.        ,  0.02427849,  0.        ,
       -0.01289268,  0.        , -0.01289268,  0.        ,  0.02227592,
        0.        ,  0.01405194,  0.00898744,  0.00113875, -0.01

In [5]:
nlp('обязанности')[0].vector

array([-0.1191054 , -0.16411726, -0.36560267,  0.29166967,  0.4109263 ,
        0.05232976, -0.20650434, -0.15334484,  0.00284027, -0.8196949 ,
        0.18733615, -0.08808075,  0.5780531 , -0.01395735,  0.29677972,
       -0.06810874, -0.184694  , -0.13320114, -0.4605594 , -0.13705982,
        0.14892071,  0.324538  ,  0.42359626, -0.58037597, -0.74658483,
       -0.31009486, -0.5068124 ,  0.72662103, -0.30160362,  0.46095592,
        0.15747736, -0.5720956 ,  0.1787494 , -0.18124358, -0.07212427,
        0.0450976 ,  0.3918063 ,  0.00340187, -0.88134617, -0.3742694 ,
       -0.01283913,  0.5566952 , -0.6461731 , -0.37998885,  0.37674773,
        0.340869  ,  0.14629763,  0.22425304, -0.02867039,  0.21361095,
       -0.511074  ,  0.03672608, -0.5207922 , -0.335089  , -0.3028759 ,
        0.18621327, -0.03594732,  0.03939559,  0.4225936 , -0.5270518 ,
       -0.62738156,  0.5651568 ,  0.43691647,  0.09875705, -0.05049898,
       -0.21782234,  0.2709053 ,  0.18158089, -0.16273092, -0.29

In [28]:
doc.tensor.shape

(97, 96)

In [23]:
from src.data.vacancy import Vacancy
from mongoengine import connect

connect('jobviz')

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, read_preference=Primary())

In [25]:
df = Vacancy.objects().limit(10).to_dataframe(include=['name', 'description', ])

In [32]:
from src.features.clean import remove_html

df.description = df.description.apply(remove_html)

In [33]:
df

_id                                        description  \
0  49810439  Обязанности: Своевременная подача автомобиля; ...   
1  49810551  Обязанности:  Уборка дома 500 кв.м., стирка, г...   
2  49810468  Студия Красоты и здоровья Кристалл ищет парикм...   
3  45788942  Условия: ЗП от 50 тысяч на руки (оклад 22 тыся...   
4  49810601  Уважаемые соискатели, рассматриваются кандидат...   
5  49810507  Логопедический Пункт 1 приглашает Администрато...   
6  49810469  Студия Красоты и здоровья Кристалл ищет парикм...   
7  49810426  Обязанности: выполнение услуг массажа на высок...   
8  47003369  Медиахолдинг "Май Медиа" ищет менеджера по про...   
9  49810583  Обязанности:  Проведение ветеринарных мероприя...   

                                          key_skills schedule.id  \
0                                                 []     fullDay   
1                     [Русский язык, Чистоплотность]     fullDay   
2  [Пользователь ПК, Работа в команде, Грамотная ...     fullDay   
3  [Складская логистика, Терминалы Сбора Данных, ...       shift   
4                                                 []     fullDay   
5  [Обучение персонала, Пользователь ПК, Организа...     fullDay   
6  [Пользователь ПК, Работа в команде, Грамотная ...     fullDay   
7  [антицеллюлитный, класический, спортивный, лим...     fullDay   
8  [Прямые продажи, Телефонные переговоры, Навыки...     fullDay   
9  [Навыки составления отчетности, Пользователь П...     fullDay   

    schedule.name experience.id     experience.name employment.id  \
0     Полный день  between3And6       От 3 до 6 лет          full   
1     Полный день  between1And3  От 1 года до 3 лет          full   
2     Полный день  between1And3  От 1 года до 3 лет          full   
3  Сменный график  noExperience           Нет опыта          full   
4     Полный день     moreThan6         Более 6 лет          full   
5     Полный день  between1And3  От 1 года до 3 лет          full   
6     Полный день  between1And3  От 1 года до 3 лет          full   
7     Полный день  between3And6       От 3 до 6 лет          full   
8     Полный день  between1And3  От 1 года до 3 лет          full   
9     Полный день  noExperience           Нет опыта          full   

    employment.name  salary.to  ...  address.metro.line_name  \
0  Полная занятость    80000.0  ...                      NaN   
1  Полная занятость   105000.0  ...            Правобережная   
2  Полная занятость        NaN  ...                      NaN   
3  Полная занятость    80000.0  ...                      NaN   
4  Полная занятость        NaN  ...                      NaN   
5  Полная занятость    30000.0  ...                      NaN   
6  Полная занятость        NaN  ...                      NaN   
7  Полная занятость   150000.0  ...    Люблинско-Дмитровская   
8  Полная занятость    70000.0  ...                      NaN   
9  Полная занятость        NaN  ...                      NaN   

  address.metro.station_id address.metro.line_id  address.metro.lat  \
0                      NaN                   NaN                NaN   
1                   17.242                    17          59.932430   
2                      NaN                   NaN                NaN   
3                      NaN                   NaN                NaN   
4                      NaN                   NaN                NaN   
5                      NaN                   NaN                NaN   
6                      NaN                   NaN                NaN   
7                   10.184                    10          55.781667   
8                      NaN                   NaN                NaN   
9                      NaN                   NaN                NaN   

  address.metro.lng                             address.metro_stations  \
0               NaN                                                NaN   
1         30.439274  [{'station_name': 'Ладожская', 'line_name': 'П...   
2               NaN                                            

In [40]:
s = 'привет'
d = nlp(s)

d[0].orth

10026568143450433331

In [42]:
nlp.vocab[d[0].orth].text

'привет'

In [43]:
import pandas as pd

df: pd.DataFrame = Vacancy.objects().to_dataframe(include=['description'])

In [53]:
df.description = df.description.map(remove_html)

In [44]:
df.shape

(36257, 1)

In [54]:
df.applymap(len).max()

description    8914
dtype: int64

In [58]:
df.description.map(len).idxmax()

26578

In [63]:
df.loc[26578][0]

'Обязанности: \u200b\u200b\u200b\u200b\u200b\u200b Выполнение функций технического заказчика по договорам для ведущих застройщиков Москвы, М.О. и прочих регионов РФ, а так же при исполнении гос. контрактов на ПИР для различных объектов нового строительства, реконструкций, кап. ремонтов ОКС, реставраций ОКН: - Сопровождение проектов по сбору ИРД, начиная с ПЗЗ, ППТ, ПМТ и ГПЗУ до сдачи объектов в эксплуатацию (тех планы, получение ЗОС, РВ, регистрация в Росреестре, получения почтового адреса) (полный цикл проекта); - Сбор и анализ исходной информации по проектам (перечень ограничений, допустимые параметры строительства и пр.), снятие и корректировка ограничений ЗУ (охранные, санитарно-защитные зоны, зоны охраны ОКН, ТУ на вынос и перекладки сетей, корректировки ЛГР, сокращения СЗЗ (ФБУЗ, РПН), постановка на учет и ликвидация ОПО в РТН и т.д.), организация оценки земельных участков на предмет параметров застройки и инженерного обеспечения будущего объекта, организация изменения ВРИ земел

In [61]:
import re

toks = re.findall('\w+', df.loc[26578][0])

In [64]:
len(toks)

1099

In [8]:
nlp.Defaults.stop_words

{'а',
 'будем',
 'будет',
 'будете',
 'будешь',
 'буду',
 'будут',
 'будучи',
 'будь',
 'будьте',
 'бы',
 'был',
 'была',
 'были',
 'было',
 'быть',
 'в',
 'вам',
 'вами',
 'вас',
 'весь',
 'во',
 'вот',
 'все',
 'всего',
 'всей',
 'всем',
 'всеми',
 'всему',
 'всех',
 'всею',
 'всея',
 'всю',
 'вся',
 'всё',
 'всём',
 'вы',
 'да',
 'для',
 'до',
 'его',
 'едим',
 'едят',
 'ее',
 'ей',
 'ел',
 'ела',
 'ем',
 'ему',
 'емъ',
 'если',
 'ест',
 'есть',
 'ешь',
 'еще',
 'ещё',
 'ею',
 'её',
 'же',
 'за',
 'и',
 'из',
 'или',
 'им',
 'ими',
 'имъ',
 'их',
 'к',
 'как',
 'кем',
 'ко',
 'когда',
 'кого',
 'ком',
 'кому',
 'комья',
 'которая',
 'которого',
 'которое',
 'которой',
 'котором',
 'которому',
 'которою',
 'которую',
 'которые',
 'который',
 'которым',
 'которыми',
 'которых',
 'кто',
 'меня',
 'мне',
 'мной',
 'мною',
 'мог',
 'моги',
 'могите',
 'могла',
 'могли',
 'могло',
 'могу',
 'могут',
 'мое',
 'моего',
 'моей',
 'моем',
 'моему',
 'моею',
 'можем',
 'может',
 'можете',
 'мо

In [38]:
nlp.vocab.vectors[list(nlp.vocab.vectors.keys())[1]]

array([ 4.58010919e-02,  8.69858146e-01, -1.62920266e-01,  7.47544095e-02,
        1.98092774e-01, -3.56788218e-01, -2.79213935e-01,  2.66844600e-01,
        2.39079997e-01,  1.40115246e-01,  4.31698561e-02, -3.53502110e-02,
       -3.55942249e-01,  1.32684618e-01,  1.38216883e-01, -2.40492195e-01,
       -3.08985591e-01,  1.95398793e-01,  1.31086648e-01,  7.97636360e-02,
        8.49877894e-02, -1.25370063e-02, -4.59028967e-02,  2.01247826e-01,
        3.21312606e-01,  3.07695568e-01,  4.22754474e-02, -7.62399197e-01,
       -4.70209926e-01,  3.73112075e-02, -3.29722911e-01, -1.22051969e-01,
       -7.53759921e-01, -3.22171658e-01,  1.12429924e-01,  6.14879746e-03,
       -3.07813883e-01, -1.51750296e-01,  1.42015278e-01,  2.83567101e-01,
        6.43486902e-02, -5.28099686e-02,  2.00429872e-01, -3.09738755e-01,
       -2.20154166e-01, -2.62519896e-01, -3.20098996e-01, -4.77824569e-01,
        2.80545000e-02,  2.26785600e-01, -2.78403491e-01,  1.02936909e-01,
       -1.17708027e-01,  

In [35]:
len(nlp.vocab.vectors.keys())

500002

In [59]:
for i, v in zip(range(200), nlp.vocab.strings):
    print(v)

	


 
  
!
!!
!!!
!!!!
!!!!!
!!!!!!
!!!!!!!
!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!
!.
!..
!...
!?
!?!?!?
!?.
!???
!Ri
!ri
!»и
"
",и
",у
"Xxxxx
"»и
"Симпсонам
"от
"по
"симпсонам
"—и
#
##ы
#gvlifestyle
#xxxx
$
$$.
$ap
%
&
&CO
&Co
&Go
&LV
&M.
&NN
&Sp
&T.
&co
&nn
&Ко
'
''
'-(
'-)
'15
'18
'97
'Or
'S
'X
'an
'im
'll
're
's
'sh
've
'x
'Ив
'Ок
'Ор
'Ши
'ат
'ор
(
(((
(*>
(*_*)
(-8
(-:
(-;
(-_-)
(-d
(._.)
(13
(46
(:
(;
(=
(>_<)
(RU
(^_^)
(o:
(x:
(x_x)
(¬_¬)
(не
(ಠ_ಠ)
(╯°□°）╯︵┻━┻
)
)))
),2
),6
),7
),а
),в
),и
),я
)-:
)-α
)/¯
)10
)11
)14
)15
)17
)18
)26
)27
)38
)52
):
)oo
)te
)УК
)до
)за
)из
)на
)не
)об
)от
)по
)со
)—с
*
**
***
****
*****
******
*******
********
*********
**********
***********
**T
**k
**t
**к
**ц
**ь
*ck
*кс
*но
*ня
*ть
*ха
*∞.
+
+0,4
+0,44
+0,461
+0,5
+0,67
+0,800
+01
+1
+1,247
+10
+11,0
+1121,7
+12
+12,0
+13
+1392,4процента
+14
+15,7
+16
+16,3
+16,5
+16,6
+17
+17,2
+17,4
+18,3
+19,8
+199
+2
+2,22
+2,55
+2.13
+208,4
+22
+22,5
+22,8
+25,1


In [65]:
nlp.vocab.vectors[4827572099774953261]

array([ 0.3115113 ,  0.44723773,  0.2927711 , -0.08193989,  0.65852875,
        0.24990997, -0.01321907,  0.03579395, -0.0397919 ,  0.00846115,
       -0.19385363, -0.30856264,  0.48339844,  0.5171593 , -0.30986997,
       -0.11273943, -0.30481702, -0.29939577, -0.4605594 , -0.13705982,
        0.14892071, -0.50242025,  0.16587807, -0.356318  ,  0.6144839 ,
        0.12309833,  0.04950386, -0.27280375, -0.07573223,  0.26447412,
       -0.5405152 , -0.3780761 ,  0.05937437, -0.05946463, -0.2638484 ,
       -0.4107988 ,  0.6627084 , -0.1732102 ,  0.07823543,  0.5322704 ,
        0.3022431 ,  0.03572848, -0.23910548,  0.6096994 ,  0.33430415,
       -0.01237269, -0.53597087, -0.34309852,  0.574828  ,  0.7090885 ,
       -0.3714245 , -0.6455978 , -0.20198114, -0.25229174, -0.30185157,
        0.9179885 ,  0.25823915, -0.31244898, -0.08696886, -0.9744559 ,
        0.6017569 , -0.10821367,  0.05855813, -0.12316786,  0.37892154,
        0.24959418, -0.28320184, -0.37297174, -0.7606852 ,  0.62

In [63]:
nlp.vocab.vectors.strings['процента']

4827572099774953261

In [79]:
nlp.vocab.vectors.strings.('процента')

'процента'

In [66]:
len([s for s in nlp.vocab.strings])

911544

In [5]:
type(nlp.vocab.vectors[4827572099774953261])

numpy.ndarray

In [43]:
len([v for v in nlp.vocab.vectors])

500002

In [101]:
# emb_vectors = []
emb = {}
emb_strings = []

for idx, v_key in enumerate(nlp.vocab.vectors):
    # emb_vectors.append(nlp.vocab.vectors[v_key])
    # emb_strings.append(nlp.vocab.strings[v_key])
    emb[v_key] = nlp.vocab.vectors[v_key]

In [100]:
all(emb[4827572099774953261] == nlp.vocab.vectors[4827572099774953261])

True

In [96]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras import Sequential
from tensorflow.keras.initializers import Constant

In [102]:
e = Sequential([
    Embedding(
        input_dim=len(emb),
        output_dim=300,
        trainable=False,
        input_length=1,
        embeddings_initializer=Constant(emb)
    )
])
e.compile('rmsprop', 'mse')

ValueError: Attempt to convert a value (<error computing repr()>) with an unsupported type (<class 'dict'>) to a Tensor.

In [ ]:
e.predict([4827572099774953261])

In [99]:
emb_vectors[1]

array([ 4.58010919e-02,  8.69858146e-01, -1.62920266e-01,  7.47544095e-02,
        1.98092774e-01, -3.56788218e-01, -2.79213935e-01,  2.66844600e-01,
        2.39079997e-01,  1.40115246e-01,  4.31698561e-02, -3.53502110e-02,
       -3.55942249e-01,  1.32684618e-01,  1.38216883e-01, -2.40492195e-01,
       -3.08985591e-01,  1.95398793e-01,  1.31086648e-01,  7.97636360e-02,
        8.49877894e-02, -1.25370063e-02, -4.59028967e-02,  2.01247826e-01,
        3.21312606e-01,  3.07695568e-01,  4.22754474e-02, -7.62399197e-01,
       -4.70209926e-01,  3.73112075e-02, -3.29722911e-01, -1.22051969e-01,
       -7.53759921e-01, -3.22171658e-01,  1.12429924e-01,  6.14879746e-03,
       -3.07813883e-01, -1.51750296e-01,  1.42015278e-01,  2.83567101e-01,
        6.43486902e-02, -5.28099686e-02,  2.00429872e-01, -3.09738755e-01,
       -2.20154166e-01, -2.62519896e-01, -3.20098996e-01, -4.77824569e-01,
        2.80545000e-02,  2.26785600e-01, -2.78403491e-01,  1.02936909e-01,
       -1.17708027e-01,  

In [3]:
nlp.vocab.strings[3623639567105129204]

'<'

In [8]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.initializers import Constant
from src.embeddings import embedding_matrix, strings
from src.settings import MAX_DESCRIPTION_WORD_COUNT

In [6]:
s = Sequential([Embedding(
    input_dim=embedding_matrix.shape[0],
    output_dim=embedding_matrix.shape[1],
    input_length=MAX_DESCRIPTION_WORD_COUNT,
    embeddings_initializer=Constant(embedding_matrix),
    trainable=False
), ])

In [10]:
a = strings[9923]
a

'professional'

In [14]:
(s.predict([9923]) == embedding_matrix[9923]).all()

True